In [3]:
import numpy as np
import numpy.linalg as la
import random
from tqdm import tqdm
import control as ct

In [4]:
def updfcn(t, x, u, params=None):
    return np.array([
        np.cos(x[2]) * u[1],
        np.sin(x[2]) * u[1],
        u[0]/r * u[1]
    ])

In [21]:
V = 1
r = 1
Q = np.diag([1,1,1])  # State cost matrix
R = np.diag([1,1])  # Control cost matrix
snake_system = ct.nlsys(updfcn)


In [28]:
rand_state = np.array([1, 2, 7*np.pi/6])
lineralized_system_rand = snake_system.linearize(rand_state,[0,1])  
K, S, E = ct.lqr(lineralized_system_rand, Q, R)
print("LQR Gain Matrix K:\n", K)

def customlinearize(x, r, u = [0.0,1.0]): #hard coded for the snake system
    A = np.array([[0, 0, -u[1] * np.sin(x[2])],
                  [0, 0, u[1] * np.cos(x[2])],
                  [0, 0, 0]])
    B = np.array([[0, np.cos(x[2])],
                  [0, np.sin(x[2])],
                  [u[1]/r, 0]]) # type: ignore
    return A, B

A, B = customlinearize(rand_state, r)

LQR Gain Matrix K:
 [[ 5.00000116e-01 -8.66025337e-01  1.73205081e+00]
 [-8.66025337e-01 -5.00000116e-01 -1.33973064e-07]]


In [29]:
print(lineralized_system_rand.A)
print(lineralized_system_rand.B)

print(A)
print(B)

[[ 0.          0.          0.50000043]
 [ 0.          0.         -0.86602515]
 [ 0.          0.          0.        ]]
[[ 0.        -0.8660254]
 [ 0.        -0.5      ]
 [ 1.         0.       ]]
[[ 0.         0.         0.5      ]
 [ 0.         0.        -0.8660254]
 [ 0.         0.         0.       ]]
[[ 0.        -0.8660254]
 [ 0.        -0.5      ]
 [ 1.         0.       ]]
